### ISSUE TITLE
Inner Fields can be hard to use in Searches

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch-groovy#25]
In a search that uses an inner object (nested or otherwise) that uses the absolute path of the field name can be difficult to use. For example, the REST API call looking for the `first` name in a document like:

```json
{
  "name" : {
    "first" : "Chris",
    "last" : "Earle"
  }
}
```

would be represented like:

```json
{
  "query" : {
    "match" : {
      "name.first" : "Chris"
    }
  }
}
```

However, the corresponding and expected Groovy version is invalid:

```groovy
SearchResponse response = client.search {
  source {
    query {
      match {
        name.first = "Chris"
      }
    }
  }
}.actionGet()
```

This results in an exception (from a local test script):

```
Caught: java.lang.NullPointerException: Cannot set property 'first' on null object
java.lang.NullPointerException: Cannot set property 'first' on null object
	at Main$_run_closure3$_closure4$_closure5$_closure6.doCall(Main.groovy:26)
	at Main$_run_closure3$_closure4$_closure5$_closure6.doCall(Main.groovy)
	at org.elasticsearch.groovy.ClosureToMapConverter.convert(ClosureToMapConverter.groovy:160)
	at org.elasticsearch.groovy.ClosureToMapConverter.mapClosure(ClosureToMapConverter.groovy:89)
	at org.elasticsearch.groovy.ClosureToMapConverter.convertValue(ClosureToMapConverter.groovy:108)
	at org.elasticsearch.groovy.ClosureToMapConverter.setProperty(ClosureToMapConverter.groovy:224)
	at org.elasticsearch.groovy.ClosureToMapConverter.invokeMethod(ClosureToMapConverter.groovy:201)
	at Main$_run_closure3$_closure4$_closure5.doCall(Main.groovy:25)
	at Main$_run_closure3$_closure4$_closure5.doCall(Main.groovy)
	at org.elasticsearch.groovy.ClosureToMapConverter.convert(ClosureToMapConverter.groovy:160)
	at org.elasticsearch.groovy.ClosureToMapConverter.mapClosure(ClosureToMapConverter.groovy:89)
	at org.elasticsearch.groovy.ClosureToMapConverter.convertValue(ClosureToMapConverter.groovy:108)
	at org.elasticsearch.groovy.ClosureToMapConverter.setProperty(ClosureToMapConverter.groovy:224)
	at org.elasticsearch.groovy.ClosureToMapConverter.invokeMethod(ClosureToMapConverter.groovy:201)
	at Main$_run_closure3$_closure4.doCall(Main.groovy:24)
	at Main$_run_closure3$_closure4.doCall(Main.groovy)
	at org.elasticsearch.groovy.ClosureToMapConverter.convert(ClosureToMapConverter.groovy:160)
	at org.elasticsearch.groovy.ClosureToMapConverter.mapClosure(ClosureToMapConverter.groovy:89)
	at org.elasticsearch.groovy.ClosureExtensions.asMap(ClosureExtensions.groovy:48)
```

------

### Workaround

Fortunately, there is a workaround to this problem in the mean time, which is to use a `Map` instead of attempting to generate it from the `Closure`:

```groovy
SearchResponse response = client.search {
  source {
    query {
      match = [
        'name.first': "Chris"
      ]
    }
  }
}.actionGet()
```

------

### Solution

The solution to the problem is that the `ClosureToMapConverter` needs to recognize the setting a property (`first` above) on an undefined property (`name` above), then combine them to effectively do exactly what you are trying to do anyway.

**Comment by pickypg** [comment]
Closed by #26. Merged PR into 1.5+ branches (1.5, 1.6, 1.x, and master).
