### ISSUE TITLE
Release ES Groovy 2.2.0

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch-groovy#35]
I am currently unable to run my tests within Gradle without disabling the security manager.

``` bash
gradle clean test -Dtests.security.manager=false
```

Until I can, then I am very hesitant to release v2.2.0. This actually appears to be [a bug in Gradle itself with how it handles the security manager related specifically to Groovy tests](https://discuss.gradle.org/t/gradle-consistently-stuck-at-test-task/14125/9?u=chris_earle). I'm hoping to see this fixed in the upcoming Gradle 2.12 release. If that happens, then ES Groovy 2.2 (and later) will require that release or later.

The Elasticsearch project has switched to using Gradle for ES 3.x (currently the master branch of both projects), and they bypass this issue by using their own customer Gradle runner. For ES Groovy 3.x, I plan to switch to that approach, but I cannot use it for 2.x builds (without a clone-and-own version, which I'd rather not support).

**Comment by ylemoigne** [comment]
Hi, gradle 2.12 is released. Do you have any news ?

**Comment by ylemoigne** [comment]
Tried to build it here with gradle 2.12, branch 2.2 (commit 2ea9a2e)

Test are freezing without security manager option :
```
Gradle Test Executor 2 started executing tests.

org.elasticsearch.groovy.action.ListenableActionFutureExtensionsTests STANDARD_OUT
    [2016-03-22 23:43:15,444][WARN ][bootstrap                ] JNA not found. native methods will be disabled.
    java.lang.ClassNotFoundException: com.sun.jna.Native
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    	at java.lang.Class.forName0(Native Method)
    	at java.lang.Class.forName(Class.java:264)
    	at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45)
    	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:89)
    	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:85)
    	at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:99)
    	at java.lang.Class.forName0(Native Method)
    	at java.lang.Class.forName(Class.java:348)
    	at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:585)
    [2016-03-22 23:43:15,447][WARN ][bootstrap                ] cannot check if running as root because JNA is not available
    [2016-03-22 23:43:15,448][WARN ][bootstrap                ] cannot install syscall filters because JNA is not available
    [2016-03-22 23:43:15,448][WARN ][bootstrap                ] cannot mlockall because JNA is not available
    [2016-03-22 23:43:15,448][WARN ][bootstrap                ] cannot register console handler because JNA is not available
> Building 50% > :test^C%
```

With the security manager option, 151 tests completed, 15 failed.

**Comment by pickypg** [comment]
Hi Yann, I think it's time to make the shift and rewrite the Gradle build to reuse Elasticsearch's build code. I was hoping to avoid that until ES 5.0 came out, but I think it's time to bite the bullet.

**Comment by ylemoigne** [comment]
Wow, that's a quick feedback :)
I understand that's not the happy path.... But there is hope you won't need to touch it while owning it.

Can we expect a release soon ?

**Comment by pickypg** [comment]
I'll try to get to that within the next week.

**Comment by pickypg** [comment]
As a side note to this issue. ES Groovy 2.1.x is compatible with ES 2.3. It's just that the builds are not working due to the security manager and time to rewrite it has been sparse.

**Comment by pickypg** [comment]
All, this has proven not worth the technical effort to attempt to rewrite the Gradle build for the 2.2, 2.3, and 2.4 branches. As a result, I have no plans to release these builds. Now that the corresponding ES issue has been merged, I am making the necessary changes so that it works with 5.x in #21773.

As a reminder, v2.1.2 _is_ compatible with ES 2.2 - 2.4 releases.
