### ISSUE TITLE
ES 5.4.3 + Grails 3 => ExtensionMethods not working

### ISSUE THREAD

**Issue by erichmx** [elastic/elasticsearch-groovy#41]
I compiled against the v5.4.3 elasticsearch tag, but when I add my jar to grails the extension methods don't work

I tried removing the extension classes that don't exist but are referenced in ttps://github.com/elastic/elasticsearch-groovy/blob/master/src/main/resources/META-INF/services/org.codehaus.groovy.runtime.ExtensionModule , and the warnings disappeared but the extension methods for search give me an error:

```
groovy.lang.MissingMethodException: No signature of method: org.elasticsearch.action.search.SearchRequest.source() is applicable for argument types: ([B) values: [[123, 34, 113, 117, 101, 114, 121, 34, 58, 123, 34, 109, 97, ...]]
Possible solutions: source(), source(org.elasticsearch.search.builder.SearchSourceBuilder), source(groovy.lang.Closure), source(groovy.lang.Closure), collect(), use([Ljava.lang.Object;)
```

Any news on a client for ES 5 published in maven??

Any idea in why the extension methods are not added??

I tried this in my BootStrap.groovy:

```java

  def addExtensionModules() {

    ClassLoader classLoader = Thread.currentThread().contextClassLoader
    new ExtensionModuleScanner(new ExtensionModuleScanner.ExtensionModuleListener() {
      @Override
      void onModule(ExtensionModule module) {
        addExtensionMethods(module)
      }
    }, classLoader).scanClasspathModules()

  }

  public static void addExtensionMethods(ExtensionModule module) {
    MetaClassRegistry metaClassRegistry = GroovySystem.getMetaClassRegistry();
    ((MetaClassRegistryImpl) metaClassRegistry).getModuleRegistry().addModule(module);
    Map classMap = new HashMap<>();
    for (MetaMethod metaMethod : module.getMetaMethods()){
      if (classMap.containsKey(metaMethod.getDeclaringClass())){
        classMap.get(metaMethod.getDeclaringClass()).add(metaMethod);
      } else {
        List methodList = new ArrayList<>();
        methodList.add(metaMethod);
        classMap.put(metaMethod.getDeclaringClass(), methodList);
      }
      if (metaMethod.isStatic()){
        ((MetaClassRegistryImpl)metaClassRegistry).getStaticMethods().add(metaMethod);
      } else {
        ((MetaClassRegistryImpl)metaClassRegistry).getInstanceMethods().add(metaMethod);
      }
      System.out.println("registered method: ${metaMethod}")
    }
    for (CachedClass cachedClass : classMap.keySet()) {
      cachedClass.addNewMopMethods(classMap.get(cachedClass));
    }
  }
```

This is the code I'm trying to run:
```java

TransportClient client = new PreBuiltTransportClient(Settings.builder()
        .put("cluster.name", "my-cluster").build())
        .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("my-server"), 9300));

String userId = "some-user-id"

// asynchronously fetch the results
ListenableActionFuture<SearchResponse> future = client.searchAsync {
  indices "documents"
  types "document"
  source {
    query {
      match {
        user.id = userId
      }
    }
  }
}

// block until the response is retrieved (you could alternatively use listeners)
SearchResponse response = future.actionGet()

```

**Comment by erichmx** [comment]
Ok, you can close this one, it was completely off. The problem is not with the extension methods, it is when it converts from a `byte[]` to a `SearchSourceBuilder`, I have no idea how that would work, but it is definitely not a problem in the wiring of the extension methods.

This line https://github.com/elastic/elasticsearch-groovy/blob/master/src/main/groovy/org/elasticsearch/groovy/action/search/SearchRequestExtensions.groovy#L39
```java
    static SearchRequest source(SearchRequest self, Closure source) {
        self.source(source.asJsonBytes())
    }
```

Gives the error:

```
  2> REPRODUCE WITH: gradle :elasticsearch-groovy:test -Dtests.seed=44295B9DE014EADB -Dtests.class=org.elasticsearch.groovy.client.IndicesAdminClientExtensionsActionTests -Dtests.method="testRefreshRequest" -Dtests.security.manager=false -Dtests.locale=es-PR -Dtests.timezone=Japan
ERROR   5.52s | IndicesAdminClientExtensionsActionTests.testRefreshRequest <<< FAILURES!
   > Throwable #1: groovy.lang.MissingMethodException: No signature of method: org.elasticsearch.action.search.SearchRequest.source() is applicable for argument types: ([B) values: [[123, 34, 113, 117, 101, 114, 121, 34, 58, 123, 34, 109, 97, ...]]
   > Possible solutions: source(), source(org.elasticsearch.search.builder.SearchSourceBuilder), source(groovy.lang.Closure), collect(), use([Ljava.lang.Object;)
   > 	at __randomizedtesting.SeedInfo.seed([44295B9DE014EADB:A934A67BEC03F379]:0)
   > 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
   > 	at org.codehaus.groovy.vmplugin.v7.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:177)
   > 	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:218)
   > 	at org.elasticsearch.groovy.action.search.SearchRequestExtensions.source(SearchRequestExtensions.groovy:39)
   > 	at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
   > 	at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:56)
   > 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
   > 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
   > 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
   > 	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:218)
   > 	at org.elasticsearch.groovy.client.IndicesAdminClientExtensionsActionTests$_testRefreshRequest_closure6.doCall(IndicesAdminClientExtensionsActionTests.groovy:102)
   > 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
   > 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
   > 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
   > 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
   > 	at groovy.lang.Closure.call(Closure.java:426)
   > 	at groovy.lang.Closure.call(Closure.java:442)
   > 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:241)
   > 	at org.codehaus.groovy.runtime.dgm$757.doMethodInvoke(Unknown Source)
   > 	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:218)
   > 	at org.elasticsearch.groovy.client.AbstractClientExtensions.doRequestAsync(AbstractClientExtensions.groovy:130)
   > 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
   > 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
   > 	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1464)
   > 	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:218)
   > 	at org.elasticsearch.groovy.client.ClientExtensions.search(ClientExtensions.groovy:744)
   > 	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:218)
   > 	at org.elasticsearch.groovy.client.IndicesAdminClientExtensionsActionTests.testRefreshRequest(IndicesAdminClientExtensionsActionTests.groovy:99)
   > 	at java.lang.Thread.run(Thread.java:748)

```
